
language: java

jdk:
  - oraclejdk8
  - oraclejdk7

install: true

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
  
before_script:
  - git fetch
  - git checkout -b gh-pages
  - git merge origin/master
  - git rm --cached --ignore-unmatch index.html

script:
  - export TEST_MODE=TRAVIS
  - export AT_HOSTNAME=$AT_HOSTNAME
  - export AT_ENCRYPTION_KEY=$AT_ENCRYPTION_KEY
  - export AT_TRANSITION_KEY=$AT_TRANSITION_KEY
  - export AT_SALT=$AT_SALT
  - gradle test

after_script:
  - git add .
  - git config user.email $GIT_EMAIL
  - git config user.name $GIT_NAME
  - git commit -m 'updating output'
  - git push -f $GIT_URL gh-pages > /dev/null 2>&1